(require 'region-bindings-mode)
(region-bindings-mode-enable)

(define-key region-bindings-mode-map "a" 'mc/mark-all-like-this)
(define-key region-bindings-mode-map "p" 'mc/mark-previous-lines)
(define-key region-bindings-mode-map "n" 'mc/mark-next-lines)
(define-key region-bindings-mode-map "P" 'mc/mark-previous-like-this)
(define-key region-bindings-mode-map "N" 'mc/mark-next-like-this)
(define-key region-bindings-mode-map "m" 'mc/mark-more-like-this-extended)
(define-key region-bindings-mode-map "q" 'query-replace-regexp)
